version: "3.5"

services:
  transmission:
    image: linuxserver/transmission
    environment:
      - TZ=Etc/UTC
    volumes:
      - ./docker/transmission/config:/config
      - ./docker/transmission/downloads:/downloads
      - ./docker/transmission/watch:/watch
    ports:
      - 19091:9091
    restart: unless-stopped
